        macro APICall
        public _\1
        _\1:
        moveq #\2,d0
        trap #\3
        endm
        
        APICall g_rect,$0,5
        APICall g_drawtext,$1,5
        APICall g_clear,$2,5
        APICall g_wherex,$3,5
        APICall g_wherey,$4,5
        APICall g_setcrs,$5,5
        APICall g_crson,$6,5
        APICall g_crsoff,$7,5
        APICall g_crshome,$8,5
        APICall g_gotoxy,$9,5
        APICall g_setclip,$a,5
        APICall g_copyclip,$b,5
        APICall g_textbox,$c,5
        APICall save_lcd,$d,5
        APICall restore_lcd,$e,5
        APICall g_drawtext_symbol,$f,5
        APICall g_drawtext_small,$10,5
        APICall g_drawtext_tiny7,$11,5
        APICall g_drawtext_tiny15,$12,5
        APICall g_drawtext_font4,$13,5
        APICall g_charwid,$14,5
        APICall g_charhei,$15,5
        APICall g_strlen,$16,5
        APICall g_setfont,$17,5
        APICall g_getfont,$18,5
        APICall g_aligntext,$19,5
        APICall API_1A_5,$1a,5
        APICall g_copybmp,$1b,5
        APICall g_cwrite,$1c,5
        APICall g_recfill,$1d,5
        APICall g_getfontwidth,$1e,5
        APICall g_copy_to,$1f,5
        APICall g_copy_from,$20,5
